name: api-de-delivery

services:
  backend:
    build:
      context: ./delivery-api
    ports:
      - "8010:8000"

  frontend:
    build:
      context: ./delivery-web
      args:
        VITE_API_BASE_URL: /api/v1
    depends_on:
      - backend
    ports:
      - "3010:80"
